coverage:
  status:
    project: off
    patch: off

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: backend
      paths:
        - api/
      statuses:
        - type: project
          target: 75%
          threshold: 1%
    - name: frontend
      paths:
        - web/
      statuses:
        - type: project
          target: auto
          threshold: 1%

comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_head: no     # default yes
  require_base: no     # default yes
  require_changes: true  # if true: only post the comment if coverage changes
